import type { Metadata } from "next";
import { mainFont } from "@/app/ui/fonts";
import "./globals.css";
import Sidebar from "./ui/Sidebar";
import SmallScreenMenu from "./ui/SmallScreenMenu";
import SiteHeader from "./ui/SiteHeader";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} antialiased`}>
        <div className="min-h-screen w-full border border-black">
          <div className="md:hidden">
            <SiteHeader />
          </div>
          <SmallScreenMenu />

          <div className="flex min-h-screen">
            <div className="hidden lg:block md:w-1/5 bg-white-bg py-5">
              <Sidebar />
            </div>
            <div className="w-full">
              <div className="md:w-full md:flex md:flex-wrap p-5 mb-20">
                <Toaster position="bottom-right" />
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
